# Generated by Django 3.2.9 on 2021-11-28 19:29

import backend.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Project name')),
                ('description', models.JSONField()),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=255, verbose_name='Theme task')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_start', models.DateTimeField(verbose_name='Date start')),
                ('date_end', models.DateTimeField(verbose_name='Date end')),
                ('update', models.DateTimeField(auto_now=True)),
                ('task_type', models.CharField(choices=[('F', 'feature'), ('B', 'bug')], db_index=True, default='F', max_length=1)),
                ('task_priority', models.CharField(choices=[('N', 'normal'), ('H', 'high'), ('U', 'urgent')], default='N', max_length=1)),
                ('estimated_time', models.PositiveSmallIntegerField(default=0, verbose_name='Estimated hours')),
                ('comments', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_picture',
            field=models.ImageField(default='user_picture/default_user_picture.png', upload_to=backend.models.upload_to_user_picture, verbose_name='Завантаження фото'),
        ),
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_time', models.PositiveSmallIntegerField(verbose_name='Spent time')),
                ('comment', models.CharField(max_length=255, verbose_name='Comment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Task', to='backend.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='performer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project', to=settings.AUTH_USER_MODEL),
        ),
    ]
