# Generated by Django 3.2.9 on 2021-12-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_task_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='comments',
            field=models.JSONField(default=list),
        ),
    ]
