# Generated by Django 3.2.9 on 2021-11-28 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20211128_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['id'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='timelog',
            options={'ordering': ['id'], 'verbose_name': 'TimeLog', 'verbose_name_plural': 'TimeLog'},
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project', to='backend.project'),
        ),
    ]
