# Generated by Django 3.2.9 on 2021-11-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20211129_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_priority',
            field=models.CharField(choices=[('normal', 'normal'), ('high', 'high'), ('urgent', 'urgent')], default='normal', max_length=6),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('feature', 'feature'), ('bug', 'bug')], db_index=True, default='feature', max_length=7),
        ),
    ]
